### ISSUE TITLE
 signature length not correct got 256 but was expecting 512

### ISSUE THREAD

**Issue by luckydogchina** [crazy-max/docker-jetbrains-license-server#9]
I run the docker-license-container in centos 7.3, the container log like this:
 ```

app_1      | Setting timezone to Europe/Paris...
app_1      | Initializing files and folders...
app_1      | Configuring Jetbrains License Server...
app_1      | Following virtual hosts will be used :
app_1      | -> jetbrains-license-server.example.com
app_1      | -> an-other-host.example.com
app_1      | Enabling User Reporting via SMTP at smtp.example.com:25...
app_1      | Setting stats sender to jetbrains@example.com...
traefik_1  | time="2018-09-11T02:54:19Z" level=info msg="Traefik version v1.6.6 built on 2018-08-20_01:10:06PM"
traefik_1  | time="2018-09-11T02:54:19Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n"
traefik_1  | time="2018-09-11T02:54:19Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc4201df5c0 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42013ac00} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik_1  | time="2018-09-11T02:54:19Z" level=info msg="Preparing server https &{Address::443 TLS:0xc42007dd80 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42013acc0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik_1  | time="2018-09-11T02:54:19Z" level=info msg="Starting server on :80"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Starting provider configuration.providerAggregator {}"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Starting server on :443"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"example.com\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false}"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Starting provider *acme.Provider {\"Email\":\"webmaster@example.com\",\"ACMELogging\":true,\"CAServer\":\"https://acme-v02.api.letsencrypt.org/directory\",\"Storage\":\"acme.json\",\"EntryPoint\":\"https\",\"OnHostRule\":true,\"OnDemand\":false,\"DNSChallenge\":null,\"HTTPChallenge\":{\"EntryPoint\":\"http\"},\"Domains\":null,\"Store\":{}}"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Testing certificate renew..."
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Server configuration reloaded on :80"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Server configuration reloaded on :443"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Server configuration reloaded on :80"
traefik_1  | time="2018-09-11T02:54:20Z" level=info msg="Server configuration reloaded on :443"
traefik_1  | time="2018-09-11T02:54:21Z" level=info msg="Skipping same configuration for provider docker"
traefik_1  | time="2018-09-11T02:54:22Z" level=info msg="Server configuration reloaded on :80"
traefik_1  | time="2018-09-11T02:54:22Z" level=info msg="Server configuration reloaded on :443"
traefik_1  | time="2018-09-11T02:54:24Z" level=info msg=Register...
traefik_1  | time="2018-09-11T02:54:25Z" level=error msg="Unable to obtain ACME certificate for domains \"jetbrains-license-server.example.com,an-other-host.example.com\" detected thanks to rule \"Host:jetbrains-license-server.example.com,an-other-host.example.com\" : cannot get ACME client acme: Error 400 - urn:ietf:params:acme:error:invalidEmail - Error creating new account :: invalid contact domain. Contact emails @example.com are forbidden"
app_1      | Setting report out of licence to 90%...
app_1      | Stats recipients: webmaster@example.com,an-other-address@example.com...
app_1      | Enabling stats via API at /0123456789ABCDEF...
app_1      | Starting JetBrains License Service...
app_1      | * Logging initialized @993ms 
app_1      | * jetty-9.3.20.v20170531 
app_1      | INFO  Config:85 - Reading classpath resource config/base.conf
app_1      | INFO  Application:63 - Recources scan took 818
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.f
app_1      | INFO  prefs:61 - Created user preferences directory.
app_1      | INFO  f:69 - Initializing from server-config.xml
app_1      | INFO  f:86 - server-config.xml is missing or corrupt. /root/.jb-license-server/server-config.xml (No such file or directory)
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.a.a
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.reporting.LicensesRunningOutNotification
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.reporting.ReportingQueue
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.reporting.ResultStorage
app_1      | INFO  Storage:39 - Results: 11/09/2018 04:46 - 11/09/2018 04:54. Last uploaded: null
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.rpc.FloatingServerRpcHandler
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.b.b
app_1      | INFO  ApplicationContext:33 - Executing startup sequence on class com.jetbrains.ls.floating.upstream.a
app_1      | * Started o.e.j.w.WebAppContext@60a7e3ec{/,file:///opt/jetbrains-license-server/web/,AVAILABLE,localhost} 
app_1      | * Started c.j.l.f.s.FakeHostsHandler@7b9ac600{/,null,AVAILABLE} 
app_1      | * Started ServerConnector@a01b32b{HTTP/1.1,[http/1.1]}{0.0.0.0:80} 
app_1      | * Started @4106ms 
app_1      | * JetBrains License Service is listening on {0.0.0.0:80} 
app_1      | WARN  pop3FetchLogger:20 - POP3 is not configured. Inbox check skipped
```
the compose file :

```
version: "3.2"

services:
  traefik:
    image: traefik:1.6-alpine
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=example.com"
      - "--acme=false"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@example.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 8080
        protocol: tcp
      - target: 443
        published: 8443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  app:
    image: crazymax/jetbrains-license-server:latest
    depends_on:
      - traefik
    volumes:
      - "jetbrains-license-server:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jetbrains-license-server"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:jetbrains-license-server.example.com,an-other-host.example.com"
    environment:
      - "TZ=Europe/Paris"
      - "JLS_VIRTUAL_HOSTS=jetbrains-license-server.example.com,an-other-host.example.com"
      - "JLS_CONTEXT=/"
      - "JLS_ACCESS_CONFIG=/data/access-config.json"
      - "JLS_STATS_RECIPIENTS=webmaster@example.com,an-other-address@example.com"
      - "JLS_REPORT_OUT_OF_LICENSE=90"
      - "JLS_SMTP_SERVER=smtp.example.com"
      - "JLS_SMTP_PORT=25"
      - "JLS_SMTP_USERNAME=smtp@example.com"
      - "JLS_SMTP_PASSWORD="
      - "JLS_STATS_FROM=jetbrains@example.com"
      - "JLS_STATS_TOKEN=0123456789ABCDEF"
    restart: always

volumes:
  jetbrains-license-server:

``` 
my docker info :
```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.11.6.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.638GiB
Name: registry.domian.novalocal
ID: 3SVZ:YNLZ:5CLX:K56M:5XBZ:WISC:GOFF:XRL2:GMS4:ZQJD:TCFQ:NL3C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
